# Basic
title: 抹茶
subtitle: 自留地
description: 欢迎来到我的个人网站~
# 头像里面的标题
avatarTitle: Mocha
# 头像里面的描述
avatarDesc: 物联网/安卓,IOS/ERP
url: "http://www.xiangnandao.com"

# Comment
comment:
    provider: duoshuo
    duoshuo:
     short_name: Mocha

# Social
social:
    #weibo: 123456789
    #weixing: kang1390305137 
    #github: MochaMM
    #twitter: 
    mail: 673890630@qq.com
    qq: 673890630
    csdn: netty

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 76b664065ab7a597cfe2474219c1c8c9 

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
# id: UA-84134159-3   
#  host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/MengZheK/kangblog.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 关于我, description: about, url: '/about'}
    - {title: 相册, description: photosindex, url: '/photosindex'}
    - {title: 时间轴, description: timeline, url: '/timeline'}
    - {title: 资源, description: ziyuan, url: '/ziyuan'}
    - {title: 留言, description: liuyan, url: '/liuyan'}      
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}       

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"


